fixed trigger
CSC207-2022F-UofT/course-project-musicmetrics pull request #27
Opened 2022-11-12 17:34 UTC by aamirhosii

2022-11-13 20:08 UTC, michaelzixizhou approved these changes

2022-11-13 20:43 UTC, maxXu0713 approved these changes

2022-11-13 21:36 UTC, dallasschn requested changes
please recommit your code without your adjustments to musicData. So only create a pull request for Alert.java

2022-11-14 00:50 UTC, dallasschn approved these changes

2022-11-14 00:57 UTC, jmlee3210 submitted a review, later dismissed

2022-11-16 22:20 UTC, dallasschn approved these changes

2022-11-17 00:23 UTC, michaelzixizhou submitted a review, later dismissed

2022-11-21 15:54 UTC, michaelzixizhou commented
Clear implementation of the code, and nice use of getting functions from other classes! I agree that getStreams should be static as it should be accessible from all other classes without an instance, since it uses weeks as a parameter already. I would suggest to write some documentation to the methods you've written to make the code readable from a glance.

2022-11-21 16:34 UTC, closed without merging